### ISSUE TITLE
Change CurrentFirmwareVersions.txt to CurrentFirmwareVersions.md

### ISSUE THREAD

**Issue by m10653** [FRC-Team-620/Warbots2022#1]
Change the CurrentFirmwareVersions.txt from a text file to a markdown file.

Use Markdown to format file to improve readability.

**Comment by m10653** [comment]
[33cee19](https://github.com/FRC-Team-620/Warbots2022/commit/33cee19bf4be762fcdd8afabc6a827d613e6e169)
Added Versions for the firmware. Roborio firmware should be included for future reference. (Uses latest firmware is not sufficient). There could be a breaking change in to the firmware for the rio or incompatibility with a new version of wpilib.

**Comment by m10653** [comment]
33cee19bf4be762fcdd8afabc6a827d613e6e169

**Comment by tjamesw123** [comment]
Sadly Mr. Combs the firmware versions for FRC robots is not publicly available so I am making do with the information I have currently.

**Comment by m10653** [comment]
Oh I Misread it. I thought it was roborio. Not radio. Yes the radio firmware is perfectly fine. My bad! Thanks!
