### ISSUE TITLE
Configurable drive code from smart dashboard.

### ISSUE THREAD

**Issue by m10653** [FRC-Team-620/Warbots2022#10]
Implement stable drive code that allows the following settings to be changed in real time with smart dashboard or glass. This is to aid drivers getting a feel for the robot.

Configurable values though smart dashboard:

- [x] Max Speed
- [ ] Control Deadzones
- [x] braking mode
- [x] ramp speed

Provide bot with this drive code running to drives and get feedback for drive controls and settings.

**Comment by tjamesw123** [comment]
Our drivers haven't yet requested a desire to control deadzones so I will leave that alone until they ask. However everything else is done.
