### ISSUE TITLE
Implement Intake Subsystem 

### ISSUE THREAD

**Issue by m10653** [FRC-Team-620/Warbots2022#11]
Implement the Intake Subsystem.  The driver should be able to just use broad commands like Intake without needing to micro manage the position of the ball within the robot. 

Touch to own: the concept of touch to own should be used. The driver should have to do no more than touch the ball with the intention to intake. The robot should handle the rest. (Stopping the intake, aligning the ball, preventing intake if ball already loaded)

**Comment by tjamesw123** [comment]
Intake is for the most part completed. The sensor is a fairly easy thing to add at a later time so I assume I will get to it soon enough.

**Comment by tjamesw123** [comment]
It maybe more practical to leave intaking to the drivers as they might want to handle it themselves. I will call this completed for now and reopen it if the drivers actually want/need touch to own with a sensor to work.
