### ISSUE TITLE
Implement Shooter Position control

### ISSUE THREAD

**Issue by m10653** [FRC-Team-620/Warbots2022#16]
Implement Shooter/turret Position control. Create and tune the control loop to aim the turret at a specific angle. Note that there may be issues with zeroing the encoder at the start of the game. May be worth asking mech to consider an absolute encoder or forcing a set starting configurating with a limit switch.

The robot should be able to demand an angle for the shooter and it should move there.

**Comment by tjamesw123** [comment]
We do still need to implement a shooter movement system so I will reopen this issue with a different goal in mind but still somewhat the same goal

**Comment by tjamesw123** [comment]
Well we ended up using soft limits and used relative encoders to track the robots rotation (hard limits might be implemented later?). But I would call this done. It doesn't have a feature for you to tell it to go to a certain angle but at the moment it doesn't need one so I am closing this issue.
