### ISSUE TITLE
Implement Shooter Speed control

### ISSUE THREAD

**Issue by m10653** [FRC-Team-620/Warbots2022#17]
Implement a control loop to speed up the shooter flywheels up to a set rpm and tune this. You may want to investigate the performance difference between a PID(only using P) or a bang bang controller. There will be a trade off of spin up speed and rpm accuracy.

https://docs.wpilib.org/en/stable/docs/software/advanced-controls/controllers/index.html

**Comment by tjamesw123** [comment]
This is also done. Nate completed it a couple of meetings ago.
