### ISSUE TITLE
Get RPM Tracking working with smartdash/setting RPM with smartdash

### ISSUE THREAD

**Issue by tjamesw123** [FRC-Team-620/Warbots2022#24]

**Comment by m10653** [comment]
Some notes that may help with RPM tracking and control.
You can get the RPM of a spark max controllers by using `spark.getEncoder().getVelocity()` This returns the RPM by default unless changed by setVelocityConversionFactor. [Docs here](https://codedocs.revrobotics.com/java/com/revrobotics/relativeencoder#getVelocity())

[Data can be pushed to network tables and smart dashboard via](https://first.wpi.edu/FRC/roborio/release2017/docs/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.html#putNumber-java.lang.String-double-)` Smartdashboard.putNumber()` This must be run within an update loop. (Does not auto update)

How to push pid loops to smart dashboard:
I just added a Helper class that allows you to add a livewindow/smart dashboard widget for the internal pid loops on the spark max controllers.
Example usage:
`SmartDashboard.putData(new SendableCANPIDController(controler.getPIDController(), ControlType.kVoltage));`

Note you will need to read the docs on how to use the PID loops within a spark max controler. (IE the set  method may not use the pid loops you may have to use setreference instead)

Also if you do not plan on using pid control there is a [BangBang controler within wpi lib](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/controllers/bang-bang.html) that may be a better fit depending on how accurate your rpm holding needs to be.

[How to Graph networktable values](https://docs.wpilib.org/en/stable/docs/software/dashboards/glass/plots.html)

**Comment by m10653** [comment]
Issue worked on in commit bdfdb9208c9e4c92ee4b545b5539fe2f2c62dfc4

Still needs to be tested.

**Comment by tjamesw123** [comment]
We ended up using bang bang controllers for this and it is done
