### ISSUE TITLE
Timed Commands LowerHooks using frames Only delay on first run.

### ISSUE THREAD

**Issue by m10653** [FRC-Team-620/Warbots2022#32]
Commands that count frames do not properly reset their frame count when the command is rerun.

Solution Properly reset frames every run. 
Or preferred just extend wpilibs [WaitCommand](https://first.wpi.edu/wpilib/allwpilib/docs/release/java/edu/wpi/first/wpilibj2/command/WaitCommand.html)

 ```
ClimberSubsystem climberSubsystem;
    protected int frames; // <-first run this is set to zero

    public LowerHooks(ClimberSubsystem climberSubsystem) {
        addRequirements(climberSubsystem);
        this.climberSubsystem = climberSubsystem;
    }

    @Override
    public void initialize() { //Next Command run frames starts at 16 and increases by one and ends after a single run of execute
        SmartDashboard.putNumber("lower hooks frams", frames);
        System.out.println("Hooks were lowered");
        climberSubsystem.getHangingSolenoid().set(true);
    }

    @Override
    public void execute() {
        frames++;
    }

    @Override
    public boolean isFinished() { //After first run it is at ~15/16
        return frames >= 15;
    }

```

**Comment by m10653** [comment]
Some commands with this bug (not exhaustive)

- [ ] LowerHooks
- [ ] LowerPistons
- [ ] RaiseHooks
- [ ] RaisePistons
- [ ] DriveBackwards
- [ ] AutoLoad
- [ ] AutoShoot
- [ ] AutoAimingAndSpinningUp

**Comment by tjamesw123** [comment]
Commands are fixed of this issue. Nate did this a bit ago.

**Comment by m10653** [comment]
This is still an issue for the DriveBackwards command.

**Comment by tjamesw123** [comment]
Wouldn't have been a problem as this command is only run once in auto but whatever it's fixed
