### ISSUE TITLE
Implement no movement robot mode for calibration. 

### ISSUE THREAD

**Issue by BCurbs** [FRC-Team-620/Warbots2022#34]
To comply with T404, in r11.4, the robot should not move any of its parts including the turret when enabled during calibration. As the code does not contain a way to enable the limelight without turning the turret, i believe we should figure this out to avoid the possible yellow card.

**Comment by m10653** [comment]
This issue/mode may be a way to do that better. #7

**Comment by BCurbs** [comment]
I don't know but we need a way to do it.
